// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAr10pOGmVx53_PJtxEgf6FuTX0-38gkrc',
    appId: '1:865363161813:web:0e5c763560619a5904e85c',
    messagingSenderId: '865363161813',
    projectId: 'fir-flutter-codelab-c1e82',
    authDomain: 'fir-flutter-codelab-c1e82.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-c1e82.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjWKZ-RkAgkyUPMpPhJC89EK7K9dn0k6I',
    appId: '1:865363161813:android:082626433cfc8a7f04e85c',
    messagingSenderId: '865363161813',
    projectId: 'fir-flutter-codelab-c1e82',
    storageBucket: 'fir-flutter-codelab-c1e82.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhdvIcXETetrD8EBFJzN2YHKy-U7DA7xs',
    appId: '1:865363161813:ios:c3cbcf01d59d116604e85c',
    messagingSenderId: '865363161813',
    projectId: 'fir-flutter-codelab-c1e82',
    storageBucket: 'fir-flutter-codelab-c1e82.appspot.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhdvIcXETetrD8EBFJzN2YHKy-U7DA7xs',
    appId: '1:865363161813:ios:65a29ae724e63a5e04e85c',
    messagingSenderId: '865363161813',
    projectId: 'fir-flutter-codelab-c1e82',
    storageBucket: 'fir-flutter-codelab-c1e82.appspot.com',
    iosBundleId: 'com.example.gtkFlutter.RunnerTests',
  );
}
